name: Python CI

on:
  push:
    branches:
      - dev_python # Trigger on push to dev_python branch
  pull_request:
    branches:
      - dev_python # Trigger on Pull Request to dev_python branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: abc1199281/DSP_lab # 指定你的 repo

    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use the latest Python 3 version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy # Install numpy
        pip install scipy # Install scipy

    - name: Run tests
      run: |
        python Ch4_SamplingOfContinuousSignal/lib/quantizing.py
        python Ch4_SamplingOfContinuousSignal/lib/estimate_snr.py
        python Others/SNR_Estimation/basic_snr_estimate.py
        # Add more test files here in the future

    # 暫時不加入 Linting，因為可能需要額外安裝工具
    # - name: Lint with flake8
    #   run: |
    #     pip install flake8
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics
